name: Schema smoke tests

on: [ push, pull_request ]

permissions: read-all

jobs:
  kubeconform:
    runs-on: ubuntu-latest
    env:
      # renovate: datasource=github-releases depName=yannh/kubeconform
      KUBECONFORM_VERSION: v0.7.0
      OCP_SCHEMA_VERSION: "4.19.0"
    steps:
      - name: Harden Runner
        uses: step-security/harden-runner@9af89fc71515a100421586dfdb3dc9c984fbf411 # v2.19.4
        with:
          egress-policy: audit

      - name: Checkout
        uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7.0.1

      - name: Validate sample manifests via kubeconform
        uses: docker://ghcr.io/yannh/kubeconform:v0.7.0@sha256:85dbef6b4b312b99133decc9c6fc9495e9fc5f92293d4ff3b7e1b30f5611823c
        with:
          args: >-
            -summary
            -kubernetes-version ${{ env.OCP_SCHEMA_VERSION }}
            -schema-location "${{ github.workspace }}/{{ .NormalizedKubernetesVersion }}/schemas/{{ .ResourceKind }}{{ .KindSuffix }}.json"
            test/fixtures/route.yaml
            test/fixtures/securitycontextconstraints.yaml
            test/fixtures/deployment.yaml
