name: Schema smoke tests

on: [ push, pull_request ]

permissions: read-all

jobs:
  kubeconform:
    runs-on: ubuntu-latest
    env:
      # renovate: datasource=github-releases depName=yannh/kubeconform
      KUBECONFORM_VERSION: v0.7.0
      OCP_SCHEMA_VERSION: "4.19.0"
    steps:
      - name: Harden Runner
        uses: step-security/harden-runner@e14015d583714f6e62063499dc959a02595150a1 # v2.21.1
        with:
          egress-policy: audit

      - name: Checkout
        uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7.0.1

      - name: Validate sample manifests via kubeconform
        run:
          make test

      - name: Validate failure sample manifests via kubeconform
        continue-on-error: true
        run:
          make test-failure
