name: Schema smoke tests

on: [ push, pull_request ]

permissions: read-all

jobs:
  kubeconform:
    runs-on: ubuntu-latest
    env:
      # renovate: datasource=github-releases depName=yannh/kubeconform
      KUBECONFORM_VERSION: v0.7.0
      OCP_SCHEMA_VERSION: "4.19.0"
    steps:
      - name: Harden Runner
        uses: step-security/harden-runner@9af89fc71515a100421586dfdb3dc9c984fbf411 # v2.19.4
        with:
          egress-policy: audit

      - name: Checkout
        uses: actions/checkout@9c091bb21b7c1c1d1991bb908d89e4e9dddfe3e0 # v7.0.0

      - name: Validate sample manifests via kubeconform
        uses: docker://ghcr.io/yannh/kubeconform:v0.8.0@sha256:faffaf43f95aa6425306e1ab8d6fcad72acb9049158f38e574c085ea1ec0f64e
        with:
          args: >-
            -summary
            -kubernetes-version ${{ env.OCP_SCHEMA_VERSION }}
            -schema-location "${{ github.workspace }}/{{ .NormalizedKubernetesVersion }}/schemas/{{ .ResourceKind }}{{ .KindSuffix }}.json"
            test/fixtures/route.yaml
            test/fixtures/securitycontextconstraints.yaml
            test/fixtures/deployment.yaml
